version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: safety-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
